# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 165c6551d25dd63fb3bd7063259506074233c22e3130178a0d88a9df688f06ff99466b6def4b7a9a26142012d86fba433c23e2e7d148497a6437292417c6e2e2

test:
  secret_key_base: 2c9e7d55279ec3734b068a8c85bb66845937f278f96a5d776a51c266cc5647b4de975121caaf239ea47c3297b7c5f6963dc9da7dc0be4866f3c4cfbede8884a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
