dist: trusty
sudo: required

language: ruby

rvm:
  - 1.9.3
  - 2.3.1

addons:
  chrome: stable

before_install:
  - gem install bundler

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://cdn.sencha.com/ext/gpl/ext-6.0.0-gpl.zip
  - unzip -q ext-6.0.0-gpl.zip
  - mv ext-6.0.0 spec/rails_app/public/extjs

script:
  - bundle exec rake

branches:
  only:
    - master
