dist: trusty
sudo: required

language: ruby

rvm:
  - 2.3.1

addons:
  chrome: stable

before_install:
  - gem install bundler

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -O extjs.zip -q ${EXTJS:-http://cdn.sencha.com/ext/gpl/ext-6.0.0-gpl.zip}
  - unzip -q extjs.zip
  - if [ -d "ext-6.0.0" ]; then
      mv ext-6.0.0 spec/rails_app/public/extjs;
    fi
  - if [ -d "ext-6.5.1" ]; then
      mv ext-6.5.1 spec/rails_app/public/extjs;
    fi

script:
  - bundle exec rake

branches:
  only:
    - master
    - 6-5-0
